// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdaoxwfbtoijbocpcatp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkYW94d2ZidG9pamJvY3BjYXRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMjkwOTAsImV4cCI6MjA2MjYwNTA5MH0.h012R2g6oIpX9Fzi_UEJbrmyYsh3_3CaON45qC4QXcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);